const Homeproduct =
[
    {
        id: 1,
        Name: 'product1',
        price: '26',
        image: 'image/L1.jpg',
        cat: 'voi sen',
        type: 'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: '96',
        image: 'image/L2.jpg',
        cat: 'voi sen',
        type: 'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: '236',
        image: 'image/L3.jpg',
        cat: 'voi sen',
        type: 'new',
    },
    {
        id: 4,
        Name: 'product4',
        price: '636',
        image: 'image/L4.jpg',
        cat: 'voi sen',
        type: 'new',
    },
    {
        id: 5,
        Name: 'product5',
        price: '98',
        image: 'image/L5.jpg',
        cat: 'voi sen',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'product6',
        price: '59',
        image: 'image/L6.jpg',
        cat: 'voi sen',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'product7',
        price: '956',
        image: 'image/L7.jpg',
        cat: 'voi sen',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'product8',
        price: '389',
        image: 'image/L8.jpg',
        cat: 'voi sen',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'product9',
        price: '67',
        image: 'image/L9.jpg',
        cat: 'voi sen',
        type: 'top',
    },
    {
        id: 10,
        Name: 'product10',
        price: '76',
        image: 'image/L10.jpg',
        cat: 'voi sen',
        type: 'top',
    },
    {
        id: 11,
        Name: 'product11',
        price: '87',
        image: 'image/L11.jpg',
        cat: 'voi sen',
        type: 'top',
    },
    {
        id: 12,
        Name: 'product12',
        price: '807',
        image: 'image/L12.jpg',
        cat: 'voi sen',
        type: 'top',
    },
    {
        id: 13,
        Name: 'product13',
        price: '807',
        image: 'image/L13.png',
        cat: 'voi sen',
        type: 'top',
    },
    {
        id: 14,
        Name: 'product14',
        price: '807',
        image: 'image/LG_1.png',
        cat: 'Guong den LED',
        type: 'top',
    },
    {
        id: 15,
        Name: 'product15',
        price: '807',
        image: 'image/LG_2.png',
        cat: 'Guong den LED',
        type: 'top',
    },
    {
        id: 16,
        Name: 'product16',
        price: '807',
        image: 'image/LG_3.png',
        cat: 'Guong den LED',
        type: 'featured',
    },
    {
        id: 17,
        Name: 'product17',
        price: '807',
        image: 'image/LG_4.png',
        cat: 'Guong den LED',
        type: 'new',
    },
    {
        id: 18,
        Name: 'product18',
        price: '507',
        image: 'image/LL_1.png',
        cat: 'LAVABO',
        type: 'top',
    },
    {
        id: 19,
        Name: 'product19',
        price: '607',
        image: 'image/LL_2.png',
        cat: 'LAVABO',
        type: 'top',
    },
    {
        id: 20,
        Name: 'product20',
        price: '407',
        image: 'image/LL_3.png',
        cat: 'LAVABO',
        type: 'new',
    },
    {
        id: 21,
        Name: 'product21',
        price: '807',
        image: 'image/LL_4.png',
        cat: 'LAVABO',
        type: 'featured',
    },
    {
        id: 22,
        Name: 'product22',
        price: '807',
        image: 'image/LL_5.png',
        cat: 'LAVABO',
        type: 'featured',
    },
    {
        id: 23,
        Name: 'product23',
        price: '907',
        image: 'image/SN_1.png',
        cat: 'bon cau',
        type: 'top',
    },
    {
        id: 24,
        Name: 'product24',
        price: '1007',
        image: 'image/SN_2.png',
        cat: 'bon cau',
        type: 'new',
    },
    {
        id: 25,
        Name: 'product25',
        price: '1207',
        image: 'image/SN_3.jpg',
        cat: 'bon cau',
        type: 'featured',
    },
    {
        id: 26,
        Name: 'product26',
        price: '307',
        image: 'image/CC1.jpg',
        cat: 'chau chen',
        type: 'top',
    },
    {
        id: 27,
        Name: 'product27',
        price: '307',
        image: 'image/CC2.jpg',
        cat: 'chau chen',
        type: 'top',
    },
    {
        id: 28,
        Name: 'product28',
        price: '407',
        image: 'image/CC3.jpg',
        cat: 'chau chen',
        type: 'new',
    },
    {
        id: 29,
        Name: 'product29',
        price: '1207',
        image: 'image/CC4.jpg',
        cat: 'chau chen',
        type: 'featured',
    },
]
export default Homeproduct
